version: 2.1
jobs:
  build:
    working_directory: ~/emojioji
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Test CI
          command: "npm run test:ci"
      - run:
          name: Test E2E
          command: npm run e2e
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - store_test_results:
          path: reports
